[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "20"

# Next.js plugin for proper API routes handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
